name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      HUSKY: 0
      HUSKY_SKIP_HOOKS: 1
    steps:
      - run: sudo timedatectl set-timezone Europe/Berlin
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_REPO_TOKEN }}
      - name: Configuring Git
        run: |
          git config --global user.name "im-it-systems"
          git config --global user.email "it-systems@instamotion.com"
      - name: Prepare dependencies
        run: npm install --ignore-scripts
      - name: Release
        run: yarn release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_REPO_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.BOT_REPO_TOKEN }}
